name: Android with Github Action - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - uses: maierj/fastlane-action@v2.2.1
        with:
          lane: 'go'
      - name: Setup build apks
        uses: actions/upload-artifact@v3
        with:
          name: Build apks
          path: app/build/outputs/apk
      - name: Setup build reports
        uses: actions/upload-artifact@v3
        with:
          name: Build reports
          path: app/build/reports
